# Generated by Django 3.2.9 on 2021-11-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20211120_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
