# Generated by Django 3.2.9 on 2021-11-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_option_answer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
